[general]

[step1]
ncpus = 8
memsize = 16384

[step2]
ncpus = 2
memsize = 16384

[step3]
ncpus = 4
memsize = 16384

[step4]
ncpus = 4
memsize = 16384

[step5]
ncpus = 4
memsize = 16384

[step6]
ncpus = 8
memsize = 32768

[step7]
ncpus = 2
memsize = 16384

[step8]
ncpus = 4
memsize = 16384

[step9]
ncpus = 4
memsize = 65536

[step9b]
ncpus = 8
memsize = 32768

[step10]
ncpus = 4
memsize = 131072

[step11]
ncpus = 1
memsize = 4096

[step12]
ncpus = 16
memsize = 131072

[step13]
ncpus = 1
memsize = 32768



[step18]
ncpus = 1
memsize = 32762

[step19]
ncpus = 1 
memsize = 16384

[step19b]
ncpus = 1
memsize = 4096

[step20]
ncpus = 1 
memsize = 16384

[step20b]
ncpus = 2
memsize = 8192